repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [json, binary]
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black-jupyter
        exclude: web/static/downloads/notebooks
  - repo: https://github.com/kynan/nbstripout
    rev: "0.5.0"
    hooks:
      - id: nbstripout
        exclude: web/static/downloads/notebooks
