theme = "hugo-theme-codex"
baseURL = "https://dfm.io/"
relativeURLs = true
languageCode = "en-us"
title = "Dan Foreman-Mackey"
copyright = "© 2014-{year} Dan Foreman-Mackey"

[params]
  github = "https://github.com/dfm"
  bluesky = "https://bsky.app/profile/dfm.io"
  email = "mailto:dfm@dfm.io"
  iconOrder = ["GitHub", "Email", "Bluesky"]
  Description = "Dan Foreman-Mackey is Research Engineer at Google DeepMind working on JAX."
  customCss = ["css/custom.css"]

[markup]
  [markup.highlight]
    codeFences = false

  [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "home"
  name = " home"
  title = "Home"
  url = "/"

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/about"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/posts"

[[menu.main]]
  identifier = "cv"
  name = "cv"
  title = "CV"
  url = "https://github.com/dfm/cv"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
