#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Ref: https://www.datisticsblog.com/2018/08/post_with_jupyter/

import re
import glob
from nbconvert.preprocessors import Preprocessor
from nbconvert import MarkdownExporter
from pathlib import Path
from traitlets.config import Config

import nbformat

inline_pat = re.compile(r"\$(.+?)\$", flags=re.M | re.S)
block_pat = re.compile(r"\$\$(.+?)\$\$", flags=re.M | re.S)


class CustomPreprocessor(Preprocessor):
    def preprocess(self, nb, resources):
        for index, cell in enumerate(nb.cells):
            if cell.cell_type == "code" and not cell.source:
                nb.cells.pop(index)
            elif cell.cell_type == "code" and cell.source.startswith(
                "%matplotlib"
            ):
                nb.cells.pop(index)
            else:
                nb.cells[index], resources = self.preprocess_cell(
                    cell, resources, index
                )
        return nb, resources

    def preprocess_cell(self, cell, resources, cell_index):
        if cell.cell_type == "code":
            cell.source = cell.source.strip()
        else:
            text = "$$".join(
                inline_pat.sub(r"`$\1$`", t) for t in cell.source.split("$$")
            )
            cell.source = block_pat.sub(r"<div>$$\1$$</div>", text)
        return cell, resources


def render_notebook(path):
    nb_path = Path(path)
    with nb_path.open() as fp:
        notebook = nbformat.read(fp, as_version=4)

    c = Config()
    c.MarkdownExporter.preprocessors = [CustomPreprocessor]
    markdown_exporter = MarkdownExporter(config=c)
    markdown, resources = markdown_exporter.from_notebook_node(notebook)

    with (Path("./content/posts") / (nb_path.name + ".md")).open("w") as f:
        f.write(markdown)

    if "outputs" in resources.keys():
        out_path = Path("./static/posts") / nb_path.stem
        if not out_path.exists():
            out_path.mkdir(parents=True)
        for key in resources["outputs"].keys():
            with (out_path / key).open("wb") as f:
                f.write(resources["outputs"][key])


if __name__ == "__main__":
    for fn in glob.glob("static/downloads/notebooks/*.ipynb"):
        render_notebook(fn)
