name: Build site

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --force --recursive
      - name: Get the existing site
        run: |
          git clone --branch main --single-branch https://github.com/dfm/dfm.github.com output
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Build
        run: |
          python -m pelican --ignore-cache content
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd output
          git add .
          git status
          git -c user.name='dfm.io-bot' -c user.email='foreman.mackey+dfm.io@gmail.com' commit -m "updating website"
          git push -q https://dfm:${GITHUB_TOKEN}@github.com/dfm/dfm.github.com.git
